services:
  api-gateway:
    image: samarkinivan/api-gateway:latest
    container_name: api-gateway
    restart: on-failure
    environment:
      APP_PORT: 8080
      ALLOWED_ORIGIN_URL: 'localhost:3000'
      AUTH_SERVICE_API_URL: 'auth-service:8081'
      ACCOUNTS_SERVICE_API_URL: 'accounts-service:8082'
      CHAT_SERVICE_API_URL: 'chat-service:8083'
      NOTIFICATIONS_SERVICE_API_URL: 'notifications-service:8084'
      AI_SERVICE_API_URL: 'ai-service:8085'
      CHAT_SERVICE_WS_URL: 'chat-service:8083'
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
    external: true
