services:
  api-gateway:
    image: samarkinivan/api-gateway:latest
    container_name: api-gateway
    restart: on-failure
    environment:
      APP_PORT: 8080
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
    external: true
